// SPDX-License-Identifier: SEE LICENSE IN LICENSE
pragma solidity 0.7.6;

string constant ERR_ACCESS_DENIED = "ERR_ACCESS_DENIED";
string constant ERR_INSUFFICIENT_ALLOWANCE = "ERR_INSUFFICIENT_ALLOWANCE";
string constant ERR_INVALID_ADDRESS = "ERR_INVALID_ADDRESS";
string constant ERR_INVALID_EXTERNAL_ADDRESS = "ERR_INVALID_EXTERNAL_ADDRESS";
string constant ERR_INVALID_FEE = "ERR_INVALID_FEE";
string constant ERR_INVALID_LENGTH = "ERR_INVALID_LENGTH";
string constant ERR_INVALID_PORTION = "ERR_INVALID_PORTION";
string constant ERR_OVERFLOW = "ERR_OVERFLOW";
string constant ERR_SAME_OWNER = "ERR_SAME_OWNER";
string constant ERR_ZERO_VALUE = "ERR_ZERO_VALUE";
