export default {
    ERR_ACCESS_DENIED: 'ERR_ACCESS_DENIED',
    ERR_INSUFFICIENT_ALLOWANCE: 'ERR_INSUFFICIENT_ALLOWANCE',
    ERR_INVALID_ADDRESS: 'ERR_INVALID_ADDRESS',
    ERR_INVALID_EXTERNAL_ADDRESS: 'ERR_INVALID_EXTERNAL_ADDRESS',
    ERR_INVALID_FEE: 'ERR_INVALID_FEE',
    ERR_INVALID_LENGTH: 'ERR_INVALID_LENGTH',
    ERR_INVALID_PORTION: 'ERR_INVALID_PORTION',
    ERR_OVERFLOW: 'ERR_OVERFLOW',
    ERR_SAME_OWNER: 'ERR_SAME_OWNER',
    ERR_ZERO_VALUE: 'ERR_ZERO_VALUE'
};
